language: go
go_import_path: qvl.io/ghbackup
go:
  - '1.10'
os:
  - linux
  - osx
after_success: |
  test "$TRAVIS_OS_NAME" = "linux" -a -n "$TRAVIS_TAG" \
  && go get github.com/goreleaser/goreleaser \
  && goreleaser
